### ISSUE TITLE
Update README and Wiki pages 

### ISSUE THREAD

**Issue by guywillis** [adaptlearning/adapt-contrib-vanilla#345]
### Subject of the issue
The current README and Wiki pages for the Vanilla plugin are out of date and require updating to be in sync with the current theme implementation.

**Comment by jroed** [comment]
Thank you for working on improving the documentation. I'm a new user, much appreciated!

I would like to propose the following:
- [Common classes](https://github.com/adaptlearning/adapt-contrib-vanilla/wiki/Custom-Classes):
   - I understood that the classes work only with bg-color, such as `bg-color black`. May be by adding some more structure to reflect the syntax it would become clearer that the other classes are values for bg-color. Otherwise people think that they can use them on their own.
   - Also add a sentence that common classes can be used everywhere, e.g. in pages, articles, blocks, components.
   - Add types and acceptable values of the classes as in the [README](https://github.com/adaptlearning/adapt-contrib-vanilla/blob/master/README.md)
- _isDividerBlock: [The wiki ](https://github.com/adaptlearning/adapt-contrib-vanilla/wiki) mentioned before that @background-color-inverted and @foreground-color-inverted are used ["but there is no styling attached to this class"](https://github.com/adaptlearning/adapt-contrib-vanilla/wiki/Visual-Enhancements). This is irritating. Could defaults be defined in _colors.less or better explained how to use _isDividerBlock?
- Add a reminder about example.json in wiki page
- [Visual Enhancements:](https://github.com/adaptlearning/adapt-contrib-vanilla/wiki/Visual-Enhancements)
  - Add related file names that should be edited in the framework (contentObjects.json etc.)

**Version**
5.22.8

**Comment by guywillis** [comment]
Thank you for your comments and feedback, @jroed 

I've been going through the documentation in [Vanilla](https://github.com/adaptlearning/adapt-contrib-vanilla/pull/371) and the [wiki](https://github.com/adaptlearning/adapt-contrib-vanilla/wiki) and it would be great to get your feedback on the changes and any comments you may have for further improvements you would recommend.

**Comment by jroed** [comment]
This wiki page about [styling your course](https://github.com/adaptlearning/adapt_framework/wiki/Styling-your-course) mentions the Vanilla theme and might also need a revision.

**Comment by guywillis** [comment]
Great suggestion @jroed

A couple of comments to highlight:

Content Object
- `header-color` and `hide-page-header` did not work for me when I added them to contentObjects.json. Can you confirm that the commands are correct? Can you test if they work for you?
    -  Both classes did work for me in the latest version. How are you applying these in your build?
- `header-color black` might be missing.
    -  It is missing, new issue [created](https://github.com/adaptlearning/adapt-contrib-vanilla/issues/372)

Components
- `comp-header-bg-color` does extend to all of the component instead of just the header for me. Can you confirm that the commands are correct? Can you test if they work for you?
    - Should only apply to the component header. If this class is applied to a text component, however, it will appear as if the background colour applies to the entire component.
- Other optional classes such as `comp-header-bg-color background` might be missing.
    - This mixin only currently supports the `black` value. New issue has been [created](https://github.com/adaptlearning/adapt-contrib-vanilla/issues/374)

I believe I have addressed the rest of your feedback from this comment but please do let me know if I can add further clarity to the wiki.

The framework wiki is definitely in need of an update.

**Comment by jroed** [comment]
@guywillis please see my comments below.

Content Object
> header-color and hide-page-header did not work for me when I added them to contentObjects.json. Can you confirm that the commands are correct? Can you test if they work for you?  Both classes did work for me in the latest version. How are you applying these in your build?

I tested it again. First I thought that the classes would affect the box menu as described [here](https://github.com/adaptlearning/adapt-contrib-boxmenu). I understood now that the classes won't affect the box menu as it only lists the content objects but does not display them. Still it is confusing as there is seemingly some overlap for the classes for `_classes` in contentObjects.json. Maybe it could be clarified in the wiki what the classes affect and what not. `hide-page-header` and `header-color background`, `transparent-dark` and `transparent-light` worked for me but not `header-color black`.
Using FW 5.22.8.

Components
> comp-header-bg-color: If this class is applied to a text component, however, it will appear as if the background colour applies to the entire component.

Yes, I tested it with a text component. Is that intended behavior? If I read header I think of headers in a sense of HTML headers. For that reason I expected `comp-header-bg-color` to only affect the header text. I understand that in most components the styling is also applied to the body. If that's what is intended then maybe a different name could be chosen to reflect what is affected by this class. Otherwise some screenshot might help to clarify. But for the text component I would expect in any case that only the header is affected as otherwise there is no difference to `bg-color`.

**Comment by jroed** [comment]
@guywillis I have the following suggestions.

[Structure](https://github.com/adaptlearning/adapt-contrib-vanilla/wiki/Structure)

Fonts
- [ ] Add reference to less file location in the following sentence 'and imported in _font-config.less' by something like 'and imported in _font-config.less (for its file location please see below in the Less section)'.

Less
- [ ] There are other files in the project folder next to theme-extras.less. Should they not also be listed? (BTW why is this folder called project?)

General comments
- [ ] What about the schema folder? If usually users should not need to edit these files I would still list it and add a similar notice as for the JS folder.
- [ ] The text for Templates should be expanded. I don't really understand what is meant with template here and how it works.

**Comment by jroed** [comment]
@guywillis Thank you for your answers and your continuing efforts to create awesome wiki pages!

I have the following suggestions.

[Icons](https://github.com/adaptlearning/adapt-contrib-vanilla/wiki/Icons)

Adding icons inline

- [ ] Would it be possible to have an image next to the `Lorem ipsum dolor sit amet <span class='icon icon-arrow-down-2 inline-icon' aria-hidden='true'></span> consectetur adipiscing elit.` example to see the output?
- [ ] Can the color of the icon be modified via an inline class?
- [ ] The image does not seem to fit as it's about 'Presentation Components'.

Icon breakdown
- [ ] In the example code `icon-arrow-down-2` is mentioned but in the icon list `arrow-down-2` provided as the icon name without the `icon-` prefix. Maybe it would be better to add the `icon-` prefix to all names in the list because then users can directly copy the names.
- [ ] Why is the Content ID relevant and how is it used?
- [ ] Currently the list is sorted by Content ID but it would be better to sort it by icon groups meaning having all types of arrows in one group together for example.
- [ ] It's fine to have the image of the icons on top of each section but even better would be to have the individual icon images next to the icon names.
- [ ] I'd suggest not to have two blocks of icons (each with the columns icon, CSS class name and content ID) in one table but rather have two separate tables. This would improve readability.

**Comment by guywillis** [comment]
Thank you for your comments above, @jroed 

I have transplanted these into a [new issue](https://github.com/adaptlearning/adapt-contrib-vanilla/issues/382) specifically for vanilla wiki updates.
